language: python
python:
  - "3.6.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
script:
  - pytest --cov-report term-missing --cov=app
  - coveralls
after-success:
  - coveralls
  - codecov --token
  - codeclimate-test-reporter
